# Form implementation generated from reading ui file 'FarsiNevis.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *
from PyQt6.QtGui import *
from arabic_reshaper import ArabicReshaper
from bidi.algorithm import get_display
import pyperclip as pc
from persiantools import digits
import webbrowser
import os
#globalVar========================================================================
checkedOrNot="0"
fSize=['8','9','10','11','12','14','16','18','20','22','24','26','28','36','48','72']
ge="گ"
che="چ"
pe="پ"
zhe="ژ"
#reshaperSeting===============================================================
reshaper = ArabicReshaper(configuration={'delete_harakat': False})
#IconPath=====================================================================
basedir = os.path.dirname(__file__)
try:
    from ctypes import windll  # Only exists on Windows.
    myappid = 'mycompany.myproduct.subproduct.version'
    windll.shell32.SetCurrentProcessExplicitAppUserModelID(myappid)
except ImportError:
    pass
#def Main=====================================================================
def harakatTrue():
   global reshaper
   reshaper = ArabicReshaper(configuration={'delete_harakat': False})
    
def harakatFales():
   global reshaper
   reshaper = ArabicReshaper(configuration={'delete_harakat': True})
    
def txtClear():
   ui.txtInput.clear()
   ui.txtOutput.clear()

#defProcessInput===================================================================
global i1
i1=""
tr=""
def ProcessInput():
   if checkedOrNot=="0":
      global i1
      a=ui.txtInput.toPlainText()
      if i1==0:
         pass
      elif i1==1:
         a=digits.en_to_fa(a)
      elif i1==2:
         a=digits.en_to_fa(a)
         a=digits.fa_to_ar(a)
      else:
         pass
      a=get_display(reshaper.reshape(a))
      ui.txtOutput.setPlainText(a)
   else:
         global tr
         tr=ui.txtInput.toPlainText()
         ui.txtOutput.setPlainText(ArFaKey())

#defcopyClipboaed===================================================================
def copyClipboaed():
    ui.txtInput.setPlainText(pc.paste())
    ProcessInput()
    pc.copy(ui.txtOutput.toPlainText())
    rep=ui.txtOutput.toPlainText()+"\n\n\nمتن کپی شد!"
    ui.txtOutput.setPlainText(rep)
#defonlyOutputCopy===================================================================
def onlyOutputCopy():
    ProcessInput()
    pc.copy(ui.txtOutput.toPlainText())
    rep=ui.txtOutput.toPlainText()+"\n\n\nمتن کپی شد!"
    ui.txtOutput.setPlainText(rep)
#defArFaKey===================================================================
def ArFaKey():
        global tr
        tr=tr.replace("آ","آ")
        tr=tr.replace("ا","ا")
        tr=tr.replace("ب","ب")
        tr=tr.replace("پ",pe)
        tr=tr.replace("ت","ت")
        tr=tr.replace("ث","ث")
        tr=tr.replace("ج","ج")
        tr=tr.replace("چ",che)
        tr=tr.replace("ه","ه")
        tr=tr.replace("د","د")
        tr=tr.replace("ذ","ذ")
        tr=tr.replace("ر","ر")
        tr=tr.replace("ز","ز")
        tr=tr.replace("ژ",zhe)
        tr=tr.replace("س","س")
        tr=tr.replace("ش","ش")
        tr=tr.replace("ص","ص")
        tr=tr.replace("ض","ض")
        tr=tr.replace("ط","ط")
        tr=tr.replace("ظ","ظ")
        tr=tr.replace("ع","ع")
        tr=tr.replace("غ","غ")
        tr=tr.replace("ف","ف")
        tr=tr.replace("ق","ق")
        tr=tr.replace("ک","کـ")
        tr=tr.replace("گ",ge)
        tr=tr.replace("ل","ل")
        tr=tr.replace("م","م")
        tr=tr.replace("ن","ن")
        tr=tr.replace("و","و")
        tr=tr.replace("ه","ه")
        tr=tr.replace("ی","ي")
        tr=tr.replace("ي‌","ى‌") # nimfasele
        tr=tr.replace("ي ","ى ")
        tr=tr.replace("ي.","ى.")
        tr=tr.replace("ي،","ى،")
        tr=tr.replace("ي:","ى:")
        tr=tr.replace("ي؛","ى؛")
        tr=tr.replace("ي!","ى!")
        tr=tr.replace("ي؟","ى؟")
        tr=tr.replace("ي(","ى(")
        tr=tr.replace("ي)","ى)")
        tr=tr.replace("ي'","ى'")
        tr=tr.replace('ي"','ى"')
        tr=tr.replace('ي«','ى«')
        tr=tr.replace('ي»','ى»')
        tr=tr.replace("ي[","ى[")
        tr=tr.replace("ي]","ى]")
        tr=tr.replace("ي{","ى{")
        tr=tr.replace("ي}","ى}")
        tr=tr.replace("ي<","ى<")
        tr=tr.replace("ي>","ى>")
        tr=tr.replace("ي*","ى*")
        tr=tr.replace("ي÷","ى÷")
        tr=tr.replace("ي×","ى×")
        tr=tr.replace("ي\n","ى\n")
        tr=tr.replace("ي.","ى.")
        if tr[-1] == "ي":
                listTr=list(tr)
                listTr[-1]="ى"
                tr=''.join(listTr)
        return tr
#UI===========================================================================
class Ui_FarsiNevis(object):
    def setupUi(self, FarsiNevis):
        FarsiNevis.setObjectName("FarsiNevis")
        FarsiNevis.resize(1120, 684)
        FarsiNevis.setMinimumSize(QtCore.QSize(1120, 684))
        FarsiNevis.setMaximumSize(QtCore.QSize(1120, 684))
        self.centralwidget = QtWidgets.QWidget(FarsiNevis)
        self.centralwidget.setObjectName("centralwidget")
#==========================================================================txtInput
        self.txtInput = QtWidgets.QTextEdit(self.centralwidget)
        self.txtInput.setGeometry(QtCore.QRect(10, 20, 1101, 261))
        self.txtInput.setObjectName("txtInput")
        self.txtInput.setFontPointSize(float(11))
#==========================================================================txtOutput
        self.txtOutput = QtWidgets.QTextEdit(self.centralwidget)
        self.txtOutput.setGeometry(QtCore.QRect(10, 390, 1101, 261))
        self.txtOutput.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.txtOutput.setObjectName("txtOutput")
        self.txtOutput.setFontPointSize(float(11))
#==========================================================================btnParcopy
        self.btnParcopy = QtWidgets.QPushButton(self.centralwidget)
        self.btnParcopy.setGeometry(QtCore.QRect(750, 290, 171, 41))
        self.btnParcopy.setAutoFillBackground(False)
        self.btnParcopy.setObjectName("btnParcopy")
        self.btnParcopy.clicked.connect(lambda:copyClipboaed())
#==========================================================================btnPardazesh
        self.btnPardazesh = QtWidgets.QPushButton(self.centralwidget)
        self.btnPardazesh.setGeometry(QtCore.QRect(390, 290, 171, 41))
        self.btnPardazesh.setObjectName("btnPardazesh")
        self.btnPardazesh.clicked.connect(lambda:ProcessInput())
#==========================================================================btnPardazeshCopy
        self.btnParOCopy = QtWidgets.QPushButton(self.centralwidget)
        self.btnParOCopy.setGeometry(QtCore.QRect(570, 290, 171, 41))
        self.btnParOCopy.setObjectName("btnParOCopy")
        self.btnParOCopy.clicked.connect(lambda:onlyOutputCopy())
#==========================================================================Clear
        self.btnClear = QtWidgets.QPushButton(self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(210, 290, 171, 41))
        self.btnClear.setObjectName("btnClear")
        self.btnClear.clicked.connect(lambda:txtClear())
#==========================================================================checkBoxAraab
        self.checkBoxAraab = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxAraab.setGeometry(QtCore.QRect(460, 340, 81, 17))
        self.checkBoxAraab.setChecked(True)
        self.checkBoxAraab.setTristate(False)
        self.checkBoxAraab.setObjectName("checkBoxAraab")
        self.checkBoxAraab.stateChanged.connect(self.checkBoxharekat)
#==========================================================================chkBoxKeyArabic
        self.chkBoxKeyArabic = QtWidgets.QCheckBox(self.centralwidget)
        self.chkBoxKeyArabic.setEnabled(True)
        self.chkBoxKeyArabic.setGeometry(QtCore.QRect(210, 340, 81, 17))
        self.chkBoxKeyArabic.setCheckable(True)
        self.chkBoxKeyArabic.setChecked(False)
        self.chkBoxKeyArabic.setTristate(False)
        self.chkBoxKeyArabic.setObjectName("chkBoxKeyArabic")
        self.chkBoxKeyArabic.stateChanged.connect(self.checkBoxKeyArabic)
#==========================================================================comboBoxTabdil
        self.comboBoxTabdil = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxTabdil.setGeometry(QtCore.QRect(560, 340, 81, 22))
        self.comboBoxTabdil.setObjectName("comboBoxTabdil")
        self.comboBoxTabdil.addItem("")
        self.comboBoxTabdil.addItem("")
        self.comboBoxTabdil.addItem("")
        self.comboBoxTabdil.currentIndexChanged.connect(self.comboTabdil)
#===========================================================================cmbFontSize
        self.cmbFontSize = QtWidgets.QComboBox(self.centralwidget)
        self.cmbFontSize.setGeometry(QtCore.QRect(930, 290, 51, 22))
        self.cmbFontSize.setEditable(True)
        self.cmbFontSize.setObjectName("cmbFontSize")
        for i in fSize:
                self.cmbFontSize.addItem(i)
        self.cmbFontSize.setCurrentText("11")
        self.cmbFontSize.currentTextChanged.connect(self.comboFontSize)
#==========================================================================cmbGe
        self.cmbGe = QtWidgets.QComboBox(self.centralwidget)
        self.cmbGe.setGeometry(QtCore.QRect(140, 290, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cmbGe.setFont(font)
        self.cmbGe.setObjectName("cmbGe")
        for i in range(11):
         self.cmbGe.addItem("")
        self.cmbGe.currentTextChanged.connect(self.cmbKeyBoardAr)
        self.cmbGe.setDisabled(True)
#==========================================================================cmbChe
        self.cmbChe = QtWidgets.QComboBox(self.centralwidget)
        self.cmbChe.setGeometry(QtCore.QRect(90, 290, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cmbChe.setFont(font)
        self.cmbChe.setObjectName("cmbChe")
        for i in range(6):
         self.cmbChe.addItem("")
        self.cmbChe.currentTextChanged.connect(self.cmbKeyBoardAr)
        self.cmbChe.setDisabled(True)
#==========================================================================cmbPe
        self.cmbPe = QtWidgets.QComboBox(self.centralwidget)
        self.cmbPe.setGeometry(QtCore.QRect(140, 330, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cmbPe.setFont(font)
        self.cmbPe.setObjectName("cmbPe")
        for i in range(7):
         self.cmbPe.addItem("")
        self.cmbPe.currentTextChanged.connect(self.cmbKeyBoardAr)
        self.cmbPe.setDisabled(True)
#==========================================================================cmbZhe
        self.cmbZhe = QtWidgets.QComboBox(self.centralwidget)
        self.cmbZhe.setGeometry(QtCore.QRect(90, 330, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cmbZhe.setFont(font)
        self.cmbZhe.setObjectName("cmbZhe")
        for i in range(8):
         self.cmbZhe.addItem("")
        self.cmbZhe.currentTextChanged.connect(self.cmbKeyBoardAr)
        self.cmbZhe.setDisabled(True)
#==========================================================================Lables
        self.lbl1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl1.setGeometry(QtCore.QRect(640, 340, 61, 20))
        self.lbl1.setObjectName("lbl1")
        self.lblOutput = QtWidgets.QLabel(self.centralwidget)
        self.lblOutput.setGeometry(QtCore.QRect(1050, 360, 47, 13))
        self.lblOutput.setObjectName("lblOutput")
        self.lblInput = QtWidgets.QLabel(self.centralwidget)
        self.lblInput.setGeometry(QtCore.QRect(1050, 0, 47, 13))
        self.lblInput.setObjectName("lblInput")
        FarsiNevis.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FarsiNevis)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        FarsiNevis.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FarsiNevis)
        self.statusbar.setObjectName("statusbar")
        FarsiNevis.setStatusBar(self.statusbar)
        
        self.acOpen = QtGui.QAction(FarsiNevis)
        self.acOpen.setCheckable(False)
        self.acOpen.setObjectName("acOpen")
        self.acOpen.setShortcut("Ctrl+O")
        
        self.acSaveas = QtGui.QAction(FarsiNevis)
        self.acSaveas.setObjectName("acSaveas")
        self.acSaveas.setShortcut("Ctrl+S")
        
        self.acTelegram = QtGui.QAction(FarsiNevis)
        self.acTelegram.setObjectName("acTelegram")
        
        self.acYT = QtGui.QAction(FarsiNevis)
        self.acYT.setObjectName("acYT")
        
        self.acGit = QtGui.QAction(FarsiNevis)
        self.acGit.setObjectName("acGit")
        
        self.menu.addAction(self.acOpen)
        self.menu.addAction(self.acSaveas)
        self.menu_2.addAction(self.acTelegram)
        self.menu_2.addAction(self.acYT)
        self.menu_2.addAction(self.acGit)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menu.triggered[QtGui.QAction].connect(self.dmenu1)
        self.menu_2.triggered[QtGui.QAction].connect(self.dmenu2)
        
        
        self.retranslateUi(FarsiNevis)
        QtCore.QMetaObject.connectSlotsByName(FarsiNevis)

    def retranslateUi(self, FarsiNevis):
        _translate = QtCore.QCoreApplication.translate
        FarsiNevis.setWindowTitle(_translate("FarsiNevis", "فارسی‌نویس"))
        self.btnParcopy.setText(_translate("FarsiNevis", "پردازش از کلیپ بورد و کپی"))
        self.btnPardazesh.setText(_translate("FarsiNevis", "پردازش"))
        self.btnClear.setText(_translate("FarsiNevis", "پاک کردن"))
        self.checkBoxAraab.setText(_translate("FarsiNevis", "دارای اعراب"))
        self.comboBoxTabdil.setItemText(0, _translate("FarsiNevis", "غیر فعال"))
        self.comboBoxTabdil.setItemText(1, _translate("FarsiNevis", "به فارسی"))
        self.comboBoxTabdil.setItemText(2, _translate("FarsiNevis", "به عربی"))
        self.lbl1.setText(_translate("FarsiNevis", "تبدیل اعداد:"))
        self.lblOutput.setText(_translate("FarsiNevis", "خروجی:"))
        self.lblInput.setText(_translate("FarsiNevis", "ورودی:"))
        self.btnParOCopy.setText(_translate("FarsiNevis", "پردازش و کپی خروجی"))
        self.cmbGe.setItemText(0, _translate("FarsiNevis", "گ"))
        self.cmbGe.setItemText(1, _translate("FarsiNevis", "كٌـ"))
        self.cmbGe.setItemText(2, _translate("FarsiNevis", "كـ"))
        self.cmbGe.setItemText(3, _translate("FarsiNevis", "كَـ"))
        self.cmbGe.setItemText(4, _translate("FarsiNevis", "كًـ"))
        self.cmbGe.setItemText(5, _translate("FarsiNevis", "كُـ"))
        self.cmbGe.setItemText(6, _translate("FarsiNevis", "كّـ"))
        self.cmbGe.setItemText(7, _translate("FarsiNevis", "كَّـ"))
        self.cmbGe.setItemText(8, _translate("FarsiNevis", "كًّـ"))
        self.cmbGe.setItemText(9, _translate("FarsiNevis", "كُّـ"))
        self.cmbGe.setItemText(10, _translate("FarsiNevis", "كٌّـ"))
        self.cmbChe.setItemText(0, _translate("FarsiNevis", "چ"))
        self.cmbChe.setItemText(1, _translate("FarsiNevis", "حٍ"))
        self.cmbChe.setItemText(2, _translate("FarsiNevis", "ج"))
        self.cmbChe.setItemText(3, _translate("FarsiNevis", "ح"))
        self.cmbChe.setItemText(4, _translate("FarsiNevis", "حِ"))
        self.cmbChe.setItemText(5, _translate("FarsiNevis", "جِ"))
        self.cmbPe.setItemText(0, _translate("FarsiNevis", "پ"))
        self.cmbPe.setItemText(1, _translate("FarsiNevis", "بِ"))
        self.cmbPe.setItemText(1, _translate("FarsiNevis", "ب"))
        self.cmbPe.setItemText(2, _translate("FarsiNevis", "بٍ"))
        self.cmbPe.setItemText(3, _translate("FarsiNevis", "يِـ"))
        self.cmbPe.setItemText(4, _translate("FarsiNevis", "يٍـ"))
        self.cmbPe.setItemText(5, _translate("FarsiNevis", "ىٍـ"))
        self.cmbPe.setItemText(6, _translate("FarsiNevis", "ىِـ"))
        self.cmbZhe.setItemText(0, _translate("FarsiNevis", "ژ"))
        self.cmbZhe.setItemText(1, _translate("FarsiNevis", "رٌ"))
        self.cmbZhe.setItemText(2, _translate("FarsiNevis", "رْ"))
        self.cmbZhe.setItemText(3, _translate("FarsiNevis", "رّ"))
        self.cmbZhe.setItemText(4, _translate("FarsiNevis", "رَْ"))
        self.cmbZhe.setItemText(5, _translate("FarsiNevis", "رَّ"))
        self.cmbZhe.setItemText(6, _translate("FarsiNevis", "رَ"))
        self.cmbZhe.setItemText(7, _translate("FarsiNevis", "رً"))
        self.chkBoxKeyArabic.setText(_translate("FarsiNevis", "عربی نویس"))
        self.menu.setTitle(_translate("FarsiNevis", "فایل"))
        self.menu_2.setTitle(_translate("FarsiNevis", "درباره ما"))
        self.acOpen.setText(_translate("FarsiNevis", "بازکردن txt"))
        self.acSaveas.setText(_translate("FarsiNevis", "ذخیره txt"))
        self.acTelegram.setText(_translate("FarsiNevis", "کانال تلگرام"))
        self.acYT.setText(_translate("FarsiNevis", "کانال یوتیوب"))
        self.acGit.setText(_translate("FarsiNevis", "صفحه گیت‌هاب"))
#=======================================================================checkBoxharekat
    def checkBoxharekat(self,checked):
      if checked:
         harakatTrue()
      else:
         harakatFales()
#=======================================================================checkBoxKeyArabic
    def checkBoxKeyArabic(self,checked):
      global checkedOrNot
      if checked:
         checkedOrNot="1"
         self.cmbGe.setDisabled(False)
         self.cmbChe.setDisabled(False)
         self.cmbPe.setDisabled(False)
         self.cmbZhe.setDisabled(False)
      else:
         checkedOrNot="0"
         self.cmbGe.setDisabled(True)
         self.cmbChe.setDisabled(True)
         self.cmbPe.setDisabled(True)
         self.cmbZhe.setDisabled(True)
#=======================================================================cmbKeyBoardAr
    def cmbKeyBoardAr(self):
      global checkedOrNot,ge,che,pe,zhe
      if checkedOrNot=="1":#0
         ge=self.cmbGe.currentText()
         che=self.cmbChe.currentText()
         pe=self.cmbPe.currentText()
         zhe=self.cmbZhe.currentText()
#=======================================================================comboTabdil
    def comboTabdil(self):
      global i1 
      i1=self.comboBoxTabdil.currentIndex() 
#=======================================================================openfiles
    def openfiles(self,f):
      fname = QFileDialog.getOpenFileName(None,f'{f}','Desktop',"Text Document(*.txt)")
      return fname[0]
#=======================================================================saveFlies
    def saveFlies(self,f):
      fname = QFileDialog.getSaveFileName(None,f'{f}','New Text Document',"Text Document(*.txt)")
      return fname[0]
#=======================================================================dmenu1
    def dmenu1(self,q):
      if q.objectName()=="acOpen":
       try:
         afile=self.openfiles("باز کردن فایل")
         print(afile)
         s=""
         with open(afile,encoding='utf8') as f:
            for line in f:
               o=line.strip()
               s=s+str(o)+"\n"
         self.txtInput.setPlainText(s)
         f.close()
       except:
          pass
      elif q.objectName()=="acSaveas":
       try:
         afile=self.saveFlies("ذخیره در") 
         with open(afile, 'w', encoding='utf-8') as f:
            f.write(self.txtOutput.toPlainText())
       except:
          pass
#=======================================================================comboFontSize
    def comboFontSize(self):
      self.txtOutput.setFontPointSize(float(self.cmbFontSize.currentText()))
      self.txtInput.setFontPointSize(float(self.cmbFontSize.currentText()))
#=======================================================================dmenu2
    def dmenu2(self,q):
      if q.objectName()=="acTelegram":
         webbrowser.open('https://t.me/sinajet')
      elif q.objectName()=="acYT":
         webbrowser.open('https://www.youtube.com/c/SinaJet')
      elif q.objectName()=="acGit":
         webbrowser.open('https://github.com/sinajet')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FarsiNevis = QtWidgets.QMainWindow()
    app.setWindowIcon(QtGui.QIcon(os.path.join(basedir,'Icon.ico')))
    ui = Ui_FarsiNevis()
    ui.setupUi(FarsiNevis)
    cb=app.clipboard()
    FarsiNevis.show()
    sys.exit(app.exec())
