# Form implementation generated from reading ui file 'FarsiNevis.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *
from PyQt6.QtGui import *
from arabic_reshaper import ArabicReshaper
import pyperclip as pc
from persiantools import digits
import webbrowser
import os
#reshaperSeting===============================================================
reshaper = ArabicReshaper(configuration={'delete_harakat': False})
#IconPath=====================================================================
basedir = os.path.dirname(__file__)
try:
    from ctypes import windll  # Only exists on Windows.
    myappid = 'mycompany.myproduct.subproduct.version'
    windll.shell32.SetCurrentProcessExplicitAppUserModelID(myappid)
except ImportError:
    pass
#def==========================================================================
def harakatTrue():
   global reshaper
   reshaper = ArabicReshaper(configuration={'delete_harakat': False})
    
def harakatFales():
   global reshaper
   reshaper = ArabicReshaper(configuration={'delete_harakat': True})
    
def txtClear():
   ui.txtInput.clear()
   ui.txtOutput.clear()


global i1
i1=""
def ProcessInput():
   global i1
   a=ui.txtInput.toPlainText()
   if i1==0:
      pass
   elif i1==1:
      a=digits.en_to_fa(a)
   elif i1==2:
      a=digits.en_to_fa(a)
      a=digits.fa_to_ar(a)
   else:
      pass
   s=""
   for k1 in a.split('\n'):
          b=reshaper.reshape(k1)
          c = b[::-1]
          s=s+c+'\n'
   ui.txtOutput.setPlainText(s)

        
def copyClipboaed():
    ui.txtInput.setPlainText(pc.paste())
    ProcessInput()
    pc.copy(ui.txtOutput.toPlainText())
    rep=ui.txtOutput.toPlainText()+"\n\n\nمتن کپی شد!"
    ui.txtOutput.setPlainText(rep)

def onlyOutputCopy():
    ProcessInput()
    pc.copy(ui.txtOutput.toPlainText())
    rep=ui.txtOutput.toPlainText()+"\n\n\nمتن کپی شد!"
    ui.txtOutput.setPlainText(rep)
        
#UI===========================================================================
class Ui_FarsiNevis(object):
    def setupUi(self, FarsiNevis):
        FarsiNevis.setObjectName("FarsiNevis")
        FarsiNevis.resize(1120, 684)
        FarsiNevis.setMinimumSize(QtCore.QSize(1120, 684))
        FarsiNevis.setMaximumSize(QtCore.QSize(1120, 684))
        self.centralwidget = QtWidgets.QWidget(FarsiNevis)
        self.centralwidget.setObjectName("centralwidget")
#==========================================================================txtInput
        self.txtInput = QtWidgets.QTextEdit(self.centralwidget)
        self.txtInput.setGeometry(QtCore.QRect(10, 20, 1101, 261))
        self.txtInput.setObjectName("txtInput")
#==========================================================================txtOutput
        self.txtOutput = QtWidgets.QTextEdit(self.centralwidget)
        self.txtOutput.setGeometry(QtCore.QRect(10, 390, 1101, 261))
        self.txtOutput.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.txtOutput.setObjectName("txtOutput")
#==========================================================================btnParcopy
        self.btnParcopy = QtWidgets.QPushButton(self.centralwidget)
        self.btnParcopy.setGeometry(QtCore.QRect(750, 290, 171, 41))
        self.btnParcopy.setAutoFillBackground(False)
        self.btnParcopy.setObjectName("btnParcopy")
        self.btnParcopy.clicked.connect(lambda:copyClipboaed())
#==========================================================================btnPardazesh
        self.btnPardazesh = QtWidgets.QPushButton(self.centralwidget)
        self.btnPardazesh.setGeometry(QtCore.QRect(390, 290, 171, 41))
        self.btnPardazesh.setObjectName("btnPardazesh")
        self.btnPardazesh.clicked.connect(lambda:ProcessInput())
#==========================================================================btnPardazeshCopy
        self.btnParOCopy = QtWidgets.QPushButton(self.centralwidget)
        self.btnParOCopy.setGeometry(QtCore.QRect(570, 290, 171, 41))
        self.btnParOCopy.setObjectName("btnParOCopy")
        self.btnParOCopy.clicked.connect(lambda:onlyOutputCopy())
#==========================================================================Clear
        self.btnClear = QtWidgets.QPushButton(self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(210, 290, 171, 41))
        self.btnClear.setObjectName("btnClear")
        self.btnClear.clicked.connect(lambda:txtClear())
#==========================================================================CheckBox
        self.checkBoxAraab = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxAraab.setGeometry(QtCore.QRect(460, 340, 81, 17))
        self.checkBoxAraab.setChecked(True)
        self.checkBoxAraab.setTristate(False)
        self.checkBoxAraab.setObjectName("checkBoxAraab")
        self.checkBoxAraab.stateChanged.connect(self.checkBoxharekat)
#==========================================================================CobmoBox
        self.comboBoxTabdil = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxTabdil.setGeometry(QtCore.QRect(560, 340, 81, 22))
        self.comboBoxTabdil.setObjectName("comboBoxTabdil")
        self.comboBoxTabdil.addItem("")
        self.comboBoxTabdil.addItem("")
        self.comboBoxTabdil.addItem("")
        self.comboBoxTabdil.currentIndexChanged.connect(self.comboTabdil)
#==========================================================================Lables
        self.lbl1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl1.setGeometry(QtCore.QRect(640, 340, 61, 20))
        self.lbl1.setObjectName("lbl1")
        self.lblOutput = QtWidgets.QLabel(self.centralwidget)
        self.lblOutput.setGeometry(QtCore.QRect(1050, 360, 47, 13))
        self.lblOutput.setObjectName("lblOutput")
        self.lblInput = QtWidgets.QLabel(self.centralwidget)
        self.lblInput.setGeometry(QtCore.QRect(1050, 0, 47, 13))
        self.lblInput.setObjectName("lblInput")
        FarsiNevis.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FarsiNevis)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        FarsiNevis.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FarsiNevis)
        self.statusbar.setObjectName("statusbar")
        FarsiNevis.setStatusBar(self.statusbar)
        
        self.acOpen = QtGui.QAction(FarsiNevis)
        self.acOpen.setCheckable(False)
        self.acOpen.setObjectName("acOpen")
        self.acOpen.setShortcut("Ctrl+O")
        
        self.acSaveas = QtGui.QAction(FarsiNevis)
        self.acSaveas.setObjectName("acSaveas")
        self.acSaveas.setShortcut("Ctrl+S")
        
        self.acTelegram = QtGui.QAction(FarsiNevis)
        self.acTelegram.setObjectName("acTelegram")
        
        self.acYT = QtGui.QAction(FarsiNevis)
        self.acYT.setObjectName("acYT")
        
        self.acGit = QtGui.QAction(FarsiNevis)
        self.acGit.setObjectName("acGit")
        
        self.menu.addAction(self.acOpen)
        self.menu.addAction(self.acSaveas)
        self.menu_2.addAction(self.acTelegram)
        self.menu_2.addAction(self.acYT)
        self.menu_2.addAction(self.acGit)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menu.triggered[QtGui.QAction].connect(self.dmenu1)
        self.menu_2.triggered[QtGui.QAction].connect(self.dmenu2)
        
        
        self.retranslateUi(FarsiNevis)
        QtCore.QMetaObject.connectSlotsByName(FarsiNevis)

    def retranslateUi(self, FarsiNevis):
        _translate = QtCore.QCoreApplication.translate
        FarsiNevis.setWindowTitle(_translate("FarsiNevis", "فارسی‌نویس"))
        self.btnParcopy.setText(_translate("FarsiNevis", "پردازش از کلیپ بورد و کپی"))
        self.btnPardazesh.setText(_translate("FarsiNevis", "پردازش"))
        self.btnClear.setText(_translate("FarsiNevis", "پاک کردن"))
        self.checkBoxAraab.setText(_translate("FarsiNevis", "دارای اعراب"))
        self.comboBoxTabdil.setItemText(0, _translate("FarsiNevis", "غیر فعال"))
        self.comboBoxTabdil.setItemText(1, _translate("FarsiNevis", "به فارسی"))
        self.comboBoxTabdil.setItemText(2, _translate("FarsiNevis", "به عربی"))
        self.lbl1.setText(_translate("FarsiNevis", "تبدیل اعداد:"))
        self.lblOutput.setText(_translate("FarsiNevis", "خروجی:"))
        self.lblInput.setText(_translate("FarsiNevis", "ورودی:"))
        self.btnParOCopy.setText(_translate("FarsiNevis", "پردازش و کپی خروجی"))
        self.menu.setTitle(_translate("FarsiNevis", "فایل"))
        self.menu_2.setTitle(_translate("FarsiNevis", "درباره ما"))
        self.acOpen.setText(_translate("FarsiNevis", "بازکردن txt"))
        self.acSaveas.setText(_translate("FarsiNevis", "ذخیره txt"))
        self.acTelegram.setText(_translate("FarsiNevis", "کانال تلگرام"))
        self.acYT.setText(_translate("FarsiNevis", "کانال یوتیوب"))
        self.acGit.setText(_translate("FarsiNevis", "صفحه گیت‌هاب"))
    def checkBoxharekat(self,checked):
        if checked:
            harakatTrue()
        else:
            harakatFales()
    
    def comboTabdil(self):
      global i1 
      i1=self.comboBoxTabdil.currentIndex() 
       
    def openfiles(self,f):
      fname = QFileDialog.getOpenFileName(None,f'{f}','Desktop',"Text Document(*.txt)")
      return fname[0]

    def saveFlies(self,f):
      fname = QFileDialog.getSaveFileName(None,f'{f}','New Text Document',"Text Document(*.txt)")
      return fname[0]
    def dmenu1(self,q):
      if q.objectName()=="acOpen":
       try:
         afile=self.openfiles("باز کردن فایل")
         print(afile)
         s=""
         with open(afile,encoding='utf8') as f:
            for line in f:
               o=line.strip()
               s=s+str(o)+"\n"
         self.txtInput.setPlainText(s)
         f.close()
       except:
          pass
      elif q.objectName()=="acSaveas":
       try:
         afile=self.saveFlies("ذخیره در") 
         with open(afile, 'w', encoding='utf-8') as f:
            f.write(self.txtOutput.toPlainText())
       except:
          pass
         
    def dmenu2(self,q):
      if q.objectName()=="acTelegram":
         webbrowser.open('https://t.me/sinajet')
      elif q.objectName()=="acYT":
         webbrowser.open('https://www.youtube.com/c/SinaJet')
      elif q.objectName()=="acGit":
         webbrowser.open('https://github.com/sinajet')
           


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FarsiNevis = QtWidgets.QMainWindow()
    app.setWindowIcon(QtGui.QIcon(os.path.join(basedir,'Icon.ico')))
    ui = Ui_FarsiNevis()
    ui.setupUi(FarsiNevis)
    cb=app.clipboard()
    FarsiNevis.show()
    sys.exit(app.exec())
